export const API_KEY = 'dd36eee247f144ba66fce886e88c3fa7';

// MOVIES
export const POPULAR_MOVIES = 'POPULAR_MOVIES';
export const UPCOMING_MOVIES = 'UPCOMING_MOVIES';
export const TOP_RATED_MOVIES = 'TOP_RATED_MOVIES';
export const NOW_PLAYING_MOVIES = 'NOW_PLAYING_MOVIES';

// TV SHOWS
export const AIRING_TODAY_SHOWS = 'LATEST_SHOWS';
export const POPULAR_SHOWS = 'POPULAR_SHOWS';
export const ON_THE_AIR_SHOWS = 'ON_THE_AIR_SHOWS';
export const TOP_RATED_SHOWS = 'TOP_RATED_SHOWS';

// SINGLE MOVIE or TV SHOW
export const SINGLE_DETAIL = 'SINGLE_DETAIL';

// SET ITEM TYPE
export const SET_ITEM_TYPE_TV = 'SET_ITEM_TYPE_TV';
export const SET_ITEM_TYPE_MOVIE = 'SET_ITEM_TYPE_MOVIE';
export const ITEM_REVIEW = 'ITEM_REVIEW';
